Quan li nha hang MVC/Models/DanhSachHoaDon.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quan_li_nha_hang_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachHoaDon
    {
        public string SoHieuHD { get; set; }
        public string NgayDat { get; set; }
        public string NgayGiao { get; set; }
        public double ThanhTien { get; set; }
        public string TenNV { get; set; }
        public string TenChucVu { get; set; }
        public int DuyetHD { get; set; }
    }
}

Quan li nha hang MVC/Controllers/HoaDonController.cs
using Quan_li_nha_hang_MVC.Models;
using Quan_li_nha_hang_MVC.Service;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using ZXing;
using ZXing.Common;

namespace Quan_li_nha_hang_MVC.Controllers
{
    public class HoaDonController : Controller
    {
        // GET: HoaDon
        public ActionResult TaoHoaDon()
        {
            HoaDonService.HuyTaoHD();
            return View();
        }
        public ActionResult HoaDonThanhToan()
        {
            using(var db= new DoAnQuanLiNHEntities())
            {
                ViewData["ban"]=db.tblBanNH.ToList();

                return View(db.tblHDOder.ToList());
            }
            
        }
       // SELECT* FROM dbo.DanhSachHD
         [HttpPost]
         public JsonResult HoaDonOderBill()
         {
            using (var db = new DoAnQuanLiNHEntities())
            {
                return Json(db.DanhSachHD.ToList());
            }
         }

       

        [HttpPost]
        public JsonResult GetListAll()
        {
            return Json(SanPhamService.ListMatHang());
        }
        public ActionResult HuyHoaDon()
        {
            HoaDonService.HuyTaoHD();
            return RedirectToAction("TaoHoaDon");
        }
        [HttpPost]
        public JsonResult GetListSua()
        {
            return Json(HoaDonService.AllPrAdd());
        }
        [HttpPost]
        public JsonResult AddData(tblMatHang model)
        {
            HoaDonService.ThemSp(model);
            return Json(HoaDonService.AllPrAdd());
        }
        [HttpPost]
        public JsonResult XoaSanPham(string id)
        {
            HoaDonService.XoaMatHang(id);
            return Json(HoaDonService.AllPrAdd());
        }
        [HttpPost]
        public JsonResult SuaData(string id, int sol)
        {
            return Json(HoaDonService.SuaSlMH(id, sol));
        }
        [HttpPost]
        public JsonResult LuuLaiHoaDon(tblHDNhapHang model)
        {
            if (HoaDonService.LuuHoaDonDT(model) > 0)
            {
                return Json("Success");
            }
            else
            {
                return Json("Error");
            }
        }
        public ActionResult DanhSachHoaDon()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ListHD()
        {
            return Json(HoaDonService.ListHoaDon());
        }
        [HttpPost]
        public JsonResult ChiTietHD(string idhd)
        {
            return Json(HoaDonService.ChitetHD(idhd));
        }
        [HttpPost]
        public JsonResult DuyetHangTheoSP(string idhd, string idh,double sl,double tientt)
        {
            string value = HoaDonService.DuyetHSanPham(idhd, idh, sl);
            if (value =="1")
            {
                return Json(HoaDonService.ChitetHD(idhd));
            }
            else
            {
                return Json("Error:"+value);
            }
        }

        public JsonResult SoHangChuaDuyet(string idhd)
        {
            using (var db= new DoAnQuanLiNHEntities())
            {
                int sohang=db.Database.SqlQuery<int>("SELECT COUNT(*) FROM dbo.tblChiTietHDNH WHERE DuyetH=0 AND ID_HDNH='"+idhd+"'").FirstOrDefault();
                return Json(sohang);
            }
        }
        [HttpPost]
        public JsonResult XoaHoaDon(string idhd)
        {
            string message= HoaDonService.XoaHoaDon(idhd);
            if (message == "1")
            {
                return Json(HoaDonService.ListHoaDon());
            }
            else
            {
                return Json("Error: "+message);
            }
        }
        [HttpPost]
        public JsonResult DuyetTatCaSP(string idhd)
        {
            if (HoaDonService.DuyetTatCaSP(idhd))
            {
                return Json("Đã xác hóa đơn thành công");
            }
            else
            {
                return Json("Đã xảy ra lỗi. Thử lại sau");
            }
        }
        public ActionResult DuyetHoaDon(string idhd)
        {
            DanhSachHoaDon ds = HoaDonService.HoaDonTheoMa(idhd) as DanhSachHoaDon;
            if (ds == null)
            {
               return RedirectToAction("DanhSachHoaDon");
            }
            else
            {
                ViewData["hoadon"] = ds;
                return View();
            }
        }
    }
}

Quan li nha hang MVC/Views/HoaDon/DuyetHoaDon.cshtml
@using System.Globalization;
@{
    ViewBag.Title = "DuyetHoaDon";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Quan_li_nha_hang_MVC.Models.DanhSachHoaDon HoaDon = ViewData["hoadon"] as Quan_li_nha_hang_MVC.Models.DanhSachHoaDon;
    string tt = "";
    if (HoaDon.DuyetHD == 0)
    {
        tt = "Chưa duyệt";
    }
    else
    {
        tt = "Đã duyệt";
    }
    CultureInfo cul = CultureInfo.GetCultureInfo("vi-VN");   // try with "en-US"
    string tien = HoaDon.ThanhTien.ToString("#,###", cul.NumberFormat);
}
<div style="margin-bottom:50px;" class="form_oder">
    <div class="formod_header">
        <div class="edit_pr_tiltle">Hóa đơn Oder</div>
        <div class="edt_item center">
            <div class="device_add">
                <div class="edit_pr_tiltle" style="font-size:18px">Thông tin hóa đơn</div>
                <div class="pr_item_work">
                    <div class="pr_txt_lb text_left">Số hiệu hóa đơn</div>
                    <div class="type_input flex_il">
                        <input type="text" id="txtshhd" class="style_item_work " value="@HoaDon.SoHieuHD" readonly />
                    </div>
                </div>
                <div class="pr_item_work">
                    <div class="pr_txt_lb text_left">Ngày đặt</div>
                    <div class="type_input flex_il">
                        <input type="text" id="txtngayd" class="style_item_work " value="@HoaDon.NgayDat.ToString().Substring(0,10)" readonly />
                    </div>
                </div>
                <div class="pr_item_work">
                    <div class="pr_txt_lb text_left">Ngày dao hàng</div>
                    <div class="type_input flex_il">
                        <input type="text" id="txtngayg" class="style_item_work " value="@HoaDon.NgayGiao.ToString().Substring(0,10)" readonly />
                    </div>
                </div>
                <div class="pr_item_work">
                    <div class="pr_txt_lb text_left">Thành tiền</div>
                    <div class="type_input flex_il">
                        <input type="text" id="txttien" class="style_item_work " value="@tien" readonly />
                    </div>
                </div>
                <div class="pr_item_work">
                    <div class="pr_txt_lb text_left">Tình trạng</div>
                    <div class="type_input flex_il">
                        <input type="text" id="txttinhtrang" class="style_item_work" value="@tt" readonly />
                    </div>
                </div>
                <div style="margin-left: 8px;" class="pr_txt_lb text_left">Người gọi</div>
                <div style="display:flex; " class="flex_list_it">
                    <div class="pr_item_work">
                        <div class="type_input flex_il">
                            <input type="text" id="txttenng" class="style_item_work " value="@HoaDon.TenNV" readonly />
                        </div>
                    </div>
                    <div class="pr_item_work">
                        <div class="type_input flex_il">
                            <input type="text" id="txtchuvu" class="style_item_work" value="@HoaDon.TenChucVu" readonly />
                        </div>
                    </div>
                </div>
                <div class="edit_pr_tiltle" style="font-size:18px">Thông tin mặt hàng</div>
            </div>
        </div>
    </div>
    <div style="padding:3px;" class="form_table">
        <table class="table">
            <thead>
                <tr style="background-color: rgb(251, 172, 1);color:white;">
                    <th style="text-align: center;">STT</th>
                    <th>Mã hàng</th>
                    <th>Tên hàng</th>
                    <th>Số lượng</th>
                    <th>Xác nhận</th>
                    <th>ĐVT</th>
                    <th>Mức giá</th>
                    <th>Loại hàng</th>
                    <th>Nhà cung cấp</th>
                    <th>Tiền</th>
                </tr>
            </thead>
            <tbody id="listsp_detail">
            </tbody>
        </table>
        <div class="device_or">
            <div class="list_btn_pr" style="margin:auto 200px;">
                <a href="~/HoaDon/DanhSachHoaDon" style="background-color: blue; color: white;" class="btn_all"> <i class="fa-solid fa-arrow-left"></i> Trở lại</a>
                <div onclick="DuyetTatCaSP();" style="background-color: blue; color: white;" class="btn_all"> <i class="fa-solid fa-check"></i> Xác nhận</div>
                <a href="~/HoaDon/TaoHoaDon" style="background-color:blue; color: white;" class="btn_all"> <i class="fa-solid fa-plus"></i> Tạo mới</a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        LoadHoaDon();
    });
    function LoadHoaDon() {
        var id = $("#txtshhd").val();
        var lisththeohd = $.ajax({
                   url: "@Url.Action("ChiTietHD", "HoaDon")",
                   method: "POST",
                   data: { idhd: id }
        });
        lisththeohd.done(function (response) {
            var html = "";
            var stt = 0;
            var tiend = 0;
            $.each(response, function (e, obj) {
                stt++;
                var tt = "";
                tiend += [obj.SoLuong] * [obj.MucGia];
                console.log(tiend);
                html += ChiTietDSHD(stt, obj)
            });
            console.log(response);

            $("#txttien").val(Number(tiend).toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,'));
            html += "<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><tr>";

            $("#listsp_detail").html(html);
        });
    }
    var sohangduyet = 0;
    var tonh = 0;
    var ttien = 0;

    function ChiTietDSHD(stt, obj) {
        var html= `<tr style="text-align: center;" >
                   <td   >` + stt + `</td>
                   <td>
                       ` + [obj.ID_Hang] + `
                   </td>
                   <td>
                      ` + [obj.TenHang] + `
                   </td>
                   <td  >
                       <input id="SP`+ [obj.ID_Hang] + `" type="text"  style="max-width:80px;height:26px;" class="style_item_work " value="` + [obj.SoLuong] + `" />
                   </td>
                   <td style="align-items: center;" >`;
        if ([obj.DuyetH] == '1') {
            html += `<div class="btn_sp" onclick="DaDuyet();" style ="background-color:green; color:#fff;" ><i class="fa-solid fa-check"></i>Duyệt</div>`;
        } else {
            html += `<div onclick = "DuyetHangTheoSP('` + [obj.ID_Hang] + `');" class="btn_sp btn_del"><i class="fa-solid fa-check"></i>Duyệt</div >`;
        }
        html += `</td>
                   <td   >
                      ` + [obj.DonViTon] + `
                   </td>
                   <td>
                      ` + [obj.MucGia] + `
                   </td>
                   <td>
                      ` + [obj.TenLoai] + `
                   </td>
                   <td>
                      ` + [obj.TenNCC] + `
                   </td>
                   <td>
                      ` + Number([obj.SoLuong] * [obj.MucGia]).toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,') + `
                   </td>
               </tr>`;
        return html;
    }

    function DaDuyet() {
        alert("Đã xác nhận số lượng sản phẩm này!");
    }
    function DuyetTatCaSP() {
        var idhd = $("#txtshhd").val();
        $.ajax({
            url: "@Url.Action("SoHangChuaDuyet", "HoaDon")",
            method: "POST",
            data: { idhd: idhd}
        }).done(function (count) {
            if (count >0) {
            customAlert.alert("Còn hàng vẫn chưa duyệt");
        }
            else {
                $.ajax({
                           url: "@Url.Action("DuyetTatCaSP", "HoaDon")",
                           method: "POST",
                           data: { idhd: idhd }
                }).done(function (response) {
                    alert(response);
                    window.location.href = "/HoaDon/DanhSachHoaDon";
                });
            }
        });

    }
    function DuyetHangTheoSP(idh) {
        var soluong = $("#SP" +idh).val();
        var idhd = $("#txtshhd").val();
        var listhdad = $.ajax({
                url: "@Url.Action("DuyetHangTheoSP", "HoaDon")",
            method: "POST",
            data: { idhd: idhd, idh: idh, sl: soluong, tientt: ttien }
        });
        var err = "Error";
        listhdad.done(function (response) {

            if (response.toString().toLowerCase().includes(err.toString().toLowerCase())) {
                alert(response);
            }
            else {
                var html = "";
                var stt = 0;
                var tiend = 0;
                $.each(response, function (e, obj) {
                    stt++;
                    var tt = "";
                    tiend += [obj.SoLuong] * [obj.MucGia];
                    console.log(tiend);
                    html += ChiTietDSHD(stt, obj)
                });
                console.log(response);

                $("#txttien").val(Number(tiend).toFixed(2).replace(/\d(?=(\d{3})+\.)/g, '$&,'));
                html += "<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><tr>";

                $("#listsp_detail").html(html);
            }
        });
    }
</script>