Quan li nha hang MVC/Models/ProductMix.cs
using FirebaseAdmin.Auth.Multitenancy;
using Quan_li_nha_hang_MVC.Service;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Globalization;
using System.Linq;
using System.Web;
using WebGrease.Css.Extensions;

namespace Quan_li_nha_hang_MVC.Models
{
    public class ProductMix
    {
        public string ID_Hang { get; set; }
        public string TenHang { get; set; }
        public string DonViTon { get; set; }
        public double MucGia { get; set; }
        public double TonDau { get; set; }
        public double NhapVe { get; set; }
        public double TonCuoi { get; set; }
        public double SuDung { get; set; }
        public string TenLoai { get; set; }
        public double PhanTram { get; set; }
        public string TenNCC { get; set; }

        public ProductMix(string iD_Hang, string tenHang, string donViTon, double mucGia,
            double tonDau, double nhapVe, double tonCuoi, double suDung, string tenLoai, double phanTram, string tenNCC)
        {
            ID_Hang = iD_Hang;
            TenHang = tenHang;
            DonViTon = donViTon;
            MucGia = mucGia;
            TonDau = tonDau;
            NhapVe = nhapVe;
            TonCuoi = tonCuoi;
            SuDung = suDung;
            TenLoai = tenLoai;
            PhanTram = phanTram;
            TenNCC = tenNCC;
        }
        public ProductMix()
        {
        }
    }
    public static class ProduceMixService
    {
        private static DoAnQuanLiNHEntities db = new DoAnQuanLiNHEntities();
        private static string NgayHomQua()
        {
            var today = DateTime.Today.AddDays(-1);
            var year = today.Year;
            var month = "";
            var day = "";
            if (today.Day.ToString().Length == 1)
            {
                day = "0" + today.Day.ToString();
            }
            if (today.Month.ToString().Length == 1)
            {
                month = "0" + today.Month.ToString();
            }
            return day + "/" + month + "/" + year;
        }
        public static List<ProductMix> GetMixList()
        {
            List<ProductMix> products = new List<ProductMix>();
            using (var dbs = new DoAnQuanLiNHEntities())
            {
                var danhsachh = db.DSAllMatHang.SqlQuery("SELECT*FROM dbo.DSAllMatHang").ToList();
                double tongdung = 0;
                foreach (DSAllMatHang mh in danhsachh.ToList())
                {
                    ProductMix product = new ProductMix();
                    product.ID_Hang = mh.ID_Hang;
                    product.TenHang = mh.TenHang;
                    product.DonViTon = mh.DonViTon;
                    product.MucGia = mh.MucGia;
                    product.TenLoai = mh.TenLoai;
                    product.TenNCC = mh.TenNCC;
                    var rest = LoadData.Instance.ExcuteScalar("EXEC dbo.TongHangDaGoiTheoNgay @ngay = '" + TonKhoService.NgayHomNay() + "',  @mah = '" + mh.ID_Hang + "'");
                    product.NhapVe = double.Parse(rest.ToString());
                    DanhSachTonHangTN_Result tonhq = db.DanhSachTonHangTN(TonKhoService.NgayHomNay()).Where(p => p.IdMH == mh.ID_Hang).FirstOrDefault();
                    if (tonhq != null)
                    {
                        product.TonCuoi = double.Parse(db.TongTienSPTonKho(TonKhoService.NgayHomNay(), tonhq.IdMH).FirstOrDefault().ToString());
                    }
                    else
                    {
                        product.TonCuoi = 0;
                    }
                    DanhSachTonHangTN_Result tonhd = db.DanhSachTonHangTN(NgayHomQua()).Where(p => p.IdMH == mh.ID_Hang).FirstOrDefault();
                    if (tonhd != null)
                    {
                        product.TonDau = double.Parse(db.TongTienSPTonKho(NgayHomQua(), tonhd.IdMH).FirstOrDefault().ToString());
                    }
                    else
                    {
                        product.TonDau = 0;
                    }
                    product.SuDung = (product.TonDau + product.NhapVe) - product.TonCuoi;
                    product.PhanTram = product.SuDung / product.TonCuoi;

                    tongdung += product.SuDung;
                    products.Add(product);
                    continue;
                }
                foreach (var product in products)
                {
                    product.PhanTram = Math.Abs( Math.Round(product.SuDung * 100 / tongdung, 3));
                    if (product.PhanTram.ToString() == "NaN")
                    {
                        product.PhanTram = 0;
                    }
                }
                return products;
            };
        }

        internal static string LuuLaiMix()
        {
            try
            {
                string maqr = "EXEC dbo.MaMixTimKiem @ngay = '"+TonKhoService.NgayHomNay()+"',@manv = 1, @note = N'Tồn kho Mix'";
                int maprmix = (int)LoadData.Instance.ExcuteScalar(maqr);
                if (maprmix == 0)
                {
                    int idprmix = (int)LoadData.Instance.ExcuteScalar("SELECT ID_Pr_Mix FROM dbo.tblProductMix WHERE NgayTon ='" + TonKhoService.NgayHomNay() +"'");
                    foreach (ProductMix pr in GetMixList())
                    {
                        if (pr.PhanTram.ToString() == "NaN")
                        {
                            pr.PhanTram = 0;
                        }
                        string query = "INSERT INTO dbo.tblCT_ProductMix" +
                            "(ID_Mix,ID_Hang,TenHang,DonViTon,GiaHang,TonKho,TonDau,NhapThuc,XuatThuc,PhanTram,TenLoai,NhaCC,SuaDoi)" +
                            "VALUES (" + idprmix + ",'" + pr.ID_Hang + "', N'" + pr.TenHang + "','" + pr.DonViTon + "'," + pr.MucGia + ",0," + pr.TonDau + ", " +
                            "" + pr.NhapVe + ",  " + pr.SuDung + ", " + pr.PhanTram.ToString().Replace(',','.') + ",  N'" + pr.TenLoai + "', N'" + pr.TenNCC + "', N'Đã lưu')";
                        LoadData.Instance.ExcuteNoneQuery(query);
                    }
                    return "1";
                }
                else
                {
                    var ketqua = "";

                    foreach (ProductMix pr in GetMixList())
                    {
                        if (pr.PhanTram.ToString() == "NaN")
                        {
                            pr.PhanTram = 0;
                        }
                        string query = "UPDATE dbo.tblCT_ProductMix SET TonKho = 0,TonDau = " + pr.TonDau + ",NhapThuc = " + pr.NhapVe + ",XuatThuc = " + pr.SuDung + "," +
                            "PhanTram =" + pr.PhanTram + " ,SuaDoi = N'Sửa đổi:" + DateTime.Now.ToString() + "' WHERE ID_Mix= '" + maprmix + "' AND ID_Hang='" + pr.ID_Hang + "'";
                        try
                        {
                           ketqua= LoadData.Instance.ExcuteNoneQuery(query).ToString();

                        }
                        catch (SqlException ex)
                        {
                            ketqua = ex.Message;
                        }                       
                    }
                    return ketqua;
                }
            }
            catch (SqlException ex)
            {
                return (ex.Message);
            }
        }


        private static string NgayHomQuaFM(DateTime ngay)
        {
            var today = ngay.AddDays(-1);
            var year = today.Year;
            var month = "";
            var day = "";
            if (today.Day.ToString().Length == 1)
            {
                day = "0" + today.Day.ToString();
            }
            else
            {
                day += today.Day.ToString();
            }
            if (today.Month.ToString().Length == 1)
            {
                month = "0" + today.Month.ToString();
            }
            else
            {
                month += today.Month.ToString();
            }
            return day + "/" + month + "/" + year;
        }
        private static string FMNgayThang(DateTime ngay)
        {
            var today = ngay;
            var year = today.Year;
            var month = "";
            var day = "";
            if (today.Day.ToString().Length == 1)
            {
                day = "0" + today.Day.ToString();
            }
            else
            {
                day += today.Day.ToString();
            }
            if (today.Month.ToString().Length == 1)
            {
                month = "0" + today.Month.ToString();
            }
            else
            {
                month += today.Month.ToString();
            }
            return day + "/" + month + "/" + year;
        }
        internal static object DanhSachMixTheoNgay(string ngay)
        {
            int idpromix = (int)LoadData.Instance.ExcuteScalar("SELECT CASE WHEN COALESCE((SELECT ID_Pr_Mix FROM dbo.tblProductMix WHERE NgayTon='" + ngay + "'),0)" +
                           " LIKE 0 THEN 0 ELSE (SELECT ID_Pr_Mix FROM dbo.tblProductMix WHERE NgayTon='" + ngay + "') END ;");
            if (idpromix == 0)
            {
                List<ProductMix> products = new List<ProductMix>();
                var ngaythang = DateTime.ParseExact(ngay, "dd/MM/yyyy",CultureInfo.InvariantCulture);
                using (var dbs = new DoAnQuanLiNHEntities())
                {
                    var danhsachh = db.DSAllMatHang.SqlQuery("SELECT*FROM dbo.DSAllMatHang").ToList();
                    var ngaychon = FMNgayThang(ngaythang).ToString();
                    var ngaytruoc = NgayHomQuaFM(ngaythang).ToString();
                    double tongdung = 0;
                    foreach (DSAllMatHang mh in danhsachh.ToList())
                    {
                        ProductMix product = new ProductMix();
                        product.ID_Hang = mh.ID_Hang;
                        product.TenHang = mh.TenHang;

Quan li nha hang MVC/Controllers/GiaoDichController.cs
using Microsoft.Azure.Management.Batch.Fluent;
using Quan_li_nha_hang_MVC.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using Syncfusion.XlsIO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;
using static Google.Cloud.Firestore.V1.StructuredAggregationQuery.Types.Aggregation.Types;
using Bytescout.Spreadsheet;
using Bytescout.Spreadsheet.Constants;
using System.Drawing;
using IApplication = Syncfusion.XlsIO.IApplication;
using System.Diagnostics;
using Quan_li_nha_hang_MVC.Service;

namespace Quan_li_nha_hang_MVC.Controllers
{
    public class GiaoDichController : Controller
    {
        // GET: GiaoDich
        public ActionResult QuanLiGiaoDich()
        {
            return View();
        }

        public JsonResult DanhSachGiaoDich()
        {
            using (var ds = new DoAnQuanLiNHEntities())
            {
                return Json(ds.DanhSachGiaoDich.ToList());
            }
        }



        public JsonResult GiaoDichTheoMa(int id)
        {
            using (var ds = new DoAnQuanLiNHEntities())
            {
                return Json(ds.DanhSachGiaoDich.Where(p => p.ID_HD_Oder == id).ToList());
            }
        }
        public ActionResult ChiTietGiaoDich(string idgd)
        {
            if (idgd == null)
            {
                return RedirectToAction("DanhSachBanDat", "DatBan");
            }
            else
            {
                ViewData["id"] = idgd;
                return View();
            }
        }
        [HttpPost]
        public JsonResult ProMixList()
        {
            var list = ProduceMixService.GetMixList().ToList() ;
            return Json(list);
        }
        [HttpPost]
        public JsonResult ProMixListDay(string ngay)
        {
            int idpromix = (int)LoadData.Instance.ExcuteScalar("SELECT CASE WHEN COALESCE((SELECT ID_Pr_Mix FROM dbo.tblProductMix WHERE NgayTon='"+ngay+"'),0)" +
                " LIKE 0 THEN 0 ELSE (SELECT ID_Pr_Mix FROM dbo.tblProductMix WHERE NgayTon='"+ngay+"') END ;");
            if(idpromix == 0)
            {
                return Json((List<ProductMix>)ProduceMixService.DanhSachMixTheoNgay(ngay));
            }
            else
            {
                return Json((List<tblCT_ProductMix>)ProduceMixService.DanhSachMixTheoNgay(ngay));
            }
           
        }

        public ActionResult ProductMixView()
        {
            return View(ProduceMixService.GetMixList());
        }
        public JsonResult LuuLaiMix()
        {
            string ketqua = ProduceMixService.LuuLaiMix();
            if (ketqua == "1")
            {
                return Json("Đã lưu thành công");
            }
            else
            {
                return Json(ketqua);
            }
        }
    }
}

Quan li nha hang MVC/Views/GiaoDich/ProductMixView.cshtml
@model IEnumerable<Quan_li_nha_hang_MVC.Models.ProductMix>

@{
    ViewBag.Title = "ProductMixView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="item_section_name">Products Mix</div>
<div style="height:128px;margin-bottom:8px;" class="product_list_work">
    <div class="pro_fint">
        <div class="device">
            <div class="pr_item_work">
                <div class="pr_txt_lb">Nhân viên Oder</div>
                <select id="cbncc" class="style_item_work">
                    <option value="Tất cả">Tất cả</option>
                </select>
            </div>
            <div class="pr_item_work">
                <div class="pr_txt_lb">Ngày</div>
                <input onchange="ProMixListDay()" id="txtngay" type="date" value="" class="style_item_work" />
            </div>
        </div>
        <div class="device">
            <div class="pr_item_work">
                <div class="pr_txt_lb">Bàn</div>
                <select id="cbtdb" onchange="ThayDoiBanTT();" class="style_item_work">
                    <option value="0">Tất cả</option>

                </select>
            </div>

        </div>
    </div>
    <div class="pr_work_user flex_il">
        <div class="device">
            <div class="pr_item_work">
                <div class="pr_txt_lb">Tổng doanh thu</div>
                <div class="type_input flex_il">
                    <input id="tongdt" class="style_item_work" type="text" readonly />

                </div>
            </div>
            <div class="pr_item_work">
                <div class="pr_txt_lb">Doanh thu hôm nay</div>
                <div class="type_input flex_il">
                    <input id="txtdttd" class="style_item_work" type="text" readonly>

                </div>
            </div>
        </div>
        <div class="device">
            <div class="device_or">
                <div style="flex-wrap:wrap;" class="list_btn_pr">
                    <div onclick=" ExportExcel();" style="background-color: green;" class="btn_all">
                        <i class="fa-solid fa-file-export"></i> Xuất Excel
                    </div>
                    <div onclick="LuuLaiMix()" style="background-color: black;" class="btn_all">
                        <i class="fa-solid fa-arrows-rotate"></i> Lưu lại
                    </div>
                    <div style="background-color: orange;" class="btn_all"><i class="fa-solid fa-circle-down"></i> Đồng bộ</div>

                </div>
            </div>
        </div>

    </div>
</div>
<div style="background-color: #fff; width: 99.6%; height: 100%;margin:auto; overflow:scroll; border-radius:5px;">
    <table id="table" class="table">
        <thead>
            <tr style="background-color: rgb(251, 172, 1);color:white;">
                <th style="text-align:center">
                    Mã hàng
                </th>
                <th>
                    Tên hàng
                </th>
                <th>
                    ĐVT
                </th>
                <th>
                    Giá hàng
                </th>
                <th>
                    Tồn đầu
                </th>
                <th>
                    Nhập thực
                </th>
                <th>
                    Tồn cuối
                </th>
                <th>
                    Xuất thực
                </th>
                <th>
                    Phần trăm
                </th>
                <th>
                    Tên loại
                </th>

                <th>
                    Nhà CC
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody id="danhsachmh">
        </tbody>
    </table>
</div>
<script src="https://cdn.jsdelivr.net/gh/linways/table-to-excel@v1.0.4/dist/tableToExcel.js"></script>
<script>


    $(document).ready(function () {

        var d = new Date(),
            month = '' + (d.getMonth() + 1),
            day = '' + d.getDate(),
            year = d.getFullYear();

        if (month.length < 2)
            month = '0' + month;
        if (day.length < 2)
            day = '0' + day;

        var fdts= [year, month, day].join('-');
        
        $("#txtngay").val(fdts);
        DSMH();
    });

    function ExportExcel() {
        var reportname = "ProductMix" + ToDay().replace("/","");

        let table = $("#table");
        TableToExcel.convert(table[0], { name: reportname+'.xlsx',  sheet: {
                name: 'Sheet 1'
            }
        });
    }

    function DSMH() {
        var html = "";
        $.ajax({
        url: "@Url.Action("ProMixList", "GiaoDich")",
            method: "POST"
        }).done(function (response) {
            $.each(response, function (e, obj) {
                html += DanhSachMatHang(obj);
            })
            $("#danhsachmh").html(html);
        }).fail(function () {
            alert('error');
        });
    }

    function FomatDate(value) {
        var today = new Date(value);
        var yyyy = today.getFullYear();
        let mm = today.getMonth() + 1;
        let dd = today.getDate();
        if (dd < 10) dd = '0' + dd;
        if (mm < 10) mm = '0' + mm;
        return (dd + '/' + mm + '/' + yyyy);
    }

    function ProMixListDay() {
        var ngayton = FomatDate( $("#txtngay").val());
          $.ajax({
            url: "@Url.Action("ProMixListDay", "GiaoDich")",
              method: "POST",
              data: { ngay: ngayton }
          }).done(function (response) {
              console.log(response);
              var html = "";
              $.each(response, function (e, obj) {
                  html += DanhSachMatHang(obj);
              });
              $("#danhsachmh").html(html);
        });
    }

    function DanhSachMatHang(item) {
            var value = "";
            if (item.SuDung < 0)
            {
                value = "#F5C6CB";
            }
            else if (item.SuDung > 3)
            {
                value = "#FFEEBA";
            }
            else
            {
                value = "#FCFCFD";
        }
        if ((item.PhanTram)=="NaN")
            {
                item.PhanTram = 0;
            }
        return `<tr style="background:`+ value+`;">
                <td style="text-align:center">
                    `+ item.ID_Hang+`
                </td>
                <td>
                    `+item.TenHang+`
                </td>
                <td>
                    `+item.DonViTon+`
                </td>
                <td style="text-align:end">
                    `+item.MucGia+`
                </td>
                <td>
                    `+item.TonDau+`
                </td>
                <td>
                    `+item.NhapVe+`
                </td>
                <td>
                    `+item.TonCuoi+`
                </td>
                <td style="`+value+`">
                    `+item.SuDung+`
                </td>
                <td>

                    `+item.PhanTram+`
                </td>
                <td>
                    `+item.TenLoai+`
                </td>
                <td>
                    `+item.TenNCC+`
                </td>
            </tr>`;
    }



    function LuuLaiMix() {
         $.ajax({
            url: "@Url.Action("LuuLaiMix", "GiaoDich")",
            method: "POST"
          }).done(function (response) {
              alert(response);
        });
    }

    function ToDay() {
        var date = new Date();
        var day = date.getDate();
        var mont = date.getMonth();
        var year = date.getFullYear();
        if (day.toString().length == 1) {
            day = "0" + day;
        }
        if (mont.toString().length == 1) {
            mont = "0" + (mont + 1);
        }
        return day+"/"+ mont +"/"+ year;
    }

    function ExportCus() {
        $.ajax({
        url: "@Url.Action("ExportExcel", "GiaoDich")",
        method: "POST"
        }).done(function (response) {
            alert(response);
        });
    }
</script>